### PR TITLE
Index map

### PR DESCRIPTION
**Pull request by abauville**
I made a map with custom markers and popups for the index page. It looks like this: Unfortunately, I didn't manage to kill the padding on the popup (the changes I made were overwritten by mapbox)

Screen Shot 2022-02-23 at 14 09 00

Screen Shot 2022-02-23 at 14 09 06

### CODE REVIEW

**Comment by markiecyt** [comment]
Branch has conflicts. Need to merge main into your branch and solve conflicts. I made a few small changes in the mapbox_controller to handle fetching distance of the studio from the users browser location.

**Comment by nairdesigns** [comment]
I am trying to view it on my own local browser, but for some reason I can't see the icons, maybe because of the conflicts?

image

**Comment by km111444** [comment]
スクリーンショット 2022-02-23 14 17 11

I can see popups.

**Comment by markiecyt** [comment]
> Branch has conflicts. Need to merge main into your branch and solve conflicts. I made a few small changes in the mapbox_controller to handle fetching distance of the studio from the users browser location.

solved

**Pull request merged**
