### PR TITLE
Add button booking show

### PR DESCRIPTION
**Pull request by markiecyt**
Updated the show a little bit to put the map next to the studio detail with a clear CTA for the button. Could still be improved but okay for now.

Also refactored the JS to use stimulus and hide the API key so that it doesn't get used by anyone else publically.

Screen Shot 2022-02-22 at 19 04 23

### CODE REVIEW

**Comment by markiecyt** [comment]
Merged another branch into here for general practice. Updated the studio cards, so this branch now contains that change as well. The card is now fully clickable and bigger.

Screen Shot 2022-02-22 at 19 24 18

**Comment by abauville** [comment]
I pulled the main, I also pulled your latest update on that branch (at 19:30). Then I checkout your branch, and went to the index and show pages of studios, and I run into a bug on both pages. It's related to mapbox. It seems you have some setup for mapbox that was not in the branch. Here's a screenshot of the error message:
Screen Shot 2022-02-22 at 19 26 14

**Comment by markiecyt** [comment]
@abauville did you run `yarn`?

**Comment by km111444** [comment]
I got the same error but after running yarn, I can see your changes! It’s nice, I like this, It makes sense where will I go after clicking on this card.

**Comment by abauville** [comment]
Indeed I didn't run yarn :p

**Comment by markiecyt** [comment]
@abauville yah I saw the same error when I install it 🤣

**Comment by abauville** [comment]
The big cards look very nice. And indeed, after yarn install, it works like a charm. I have a couple of final suggestions:
1. I think the name is important and should be there. If you want to keep the card light you can replace the address with the name on the studios page. Especially, if we put the map on the studios page, the address is redundant.
2. Also, I think we don't need to write "Price: ": if you see 1500Y/hr on the card it is already obvious that it is the price.

What do you think? Make the modif (or not), and let's merge this branch!

**Comment by markiecyt** [comment]
@abauville Yes, you are right, I removed the 'price' 😂.  yah, that's a good point too. For today, we will definitely show the map on the show page for a single studio. Let's stick with the original design for now. After today's pitch, when we have time, we can add the map to the index page as well(nice to have), then we can just keep the name and price on the card. Thanks!

**Pull request merged**
