### PR TITLE
fixed the show page

### PR DESCRIPTION
**Pull request by nairdesigns**
it is a little bit pixilated like markie said, but what do you all think

image

### CODE REVIEW

**Comment by nairdesigns** [comment]
another pixilation example

image

**Comment by nairdesigns** [comment]
image
image

**Comment by abauville** [comment]
Maybe I'm biased because I've seen the thin booking form so many times, but I think it would look better with a thinner form and a bigger picture, like 2/3 picture, 1/3 form

**Comment by nairdesigns** [comment]
> Maybe I'm biased because I've seen the thin booking form so many times, but I think it would look better with a thinner form and a bigger picture, like 2/3 picture, 1/3 form

Okay! i can work on that

**Pull request merged**
