### PR TITLE
Minor front end changes

### PR DESCRIPTION
**Pull request by nairdesigns**
added a button with a  cool hover effect  that turns light blue.

also fixed the margin on the studios index page

image

image

image

### CODE REVIEW

**Comment by markiecyt** [comment]
Hey Brian, make sure you keep your main updated. Your branch is missing code (in the navbar for example). Your branch also has conflicts so can't be merged.

**Comment by abauville** [comment]
I like the general vibe of the button with the thick white border. Right now, the text is a bit hard to read, so you could ask a dark transparent background to make the white text stand out, maybe some text-shadow as well. Also, we should homogenize the visual aspect. e.g the sign-out button is a rounded pill but the main button has sharp edges. 
Markie used border-radius=16px on the cards. I propose we use that as our standard.

**Comment by nairdesigns** [comment]
> Hey Brian, make sure you keep your main updated. Your branch is missing code (in the navbar for example). Your branch also has conflicts so can't be merged.

Understood! I keep forgetting to do that, i'll try to do a quick fix

**Comment by nairdesigns** [comment]
> I like the general vibe of the button with the thick white border. Right now, the text is a bit hard to read, so you could ask a dark transparent background to make the white text stand out, maybe some text-shadow as well. Also, we should homogenize the visual aspect. e.g the sign-out button is a rounded pill but the main button has sharp edges. Markie used border-radius=16px on the cards. I propose we use that as our standard.

thank you, Arthur! I'll add some text shadow as well as a filter to make the image darker, and I completely agree about keeping it all generally homogeneous, I'll try to stick to the theme, thanks!

**Comment by nairdesigns** [comment]
I tried to give the button a smoother circular feature, but it would mess up with the animation and give this weird circle rectangle hybrid

image
image
image

**Comment by nairdesigns** [comment]
just changed it, should have no more conflicts.

image

**Pull request merged**
