### PR TITLE
replaced checkboxes with dropdowns for start and end times

### PR DESCRIPTION
**Pull request by abauville**
I replaced the checkboxes with two dropdown menus to select the start and end times. I added some JS to ensure that only end times at least one hour after the start time can be selected.

Screen Shot 2022-02-25 at 8 28 16

### CODE REVIEW

**Comment by markiecyt** [comment]
It looks better. Could you please change the style so it matches the other input?

**Comment by nairdesigns** [comment]
image

**Comment by abauville** [comment]
Fixed the border-radius and moved the dropdown boxes next to each other
As suggested by Markie I passed Date.today to the new booking. Also I m
Screen Shot 2022-02-25 at 12 37 09
oved the new booking definition from the view to the studios controller#show.

**Comment by markiecyt** [comment]
Looks great!

**Pull request merged**
